### ISSUE TITLE
Weird snappy animations

### ISSUE THREAD

**Issue by RWOverdijk** [react-navigation/animated-switch#1]
I've written about this more in this issue: https://github.com/kmagiera/react-native-reanimated/issues/231

I'm not entirely sure what the cause could be, which library might be causing this or if it's my own code even. But I also don't know where to start looking.

Does react-navigation-animated-switch do anything that could cause my animations to go crazy right before transitioning out?

**Comment by brentvatne** [comment]
it'd be good to create a reproducible example of what you're seeing here, and also explain what platform you're seeing it on. i haven't seen such a thing in my brief experiments

**Comment by iRoachie** [comment]
I’ve experienced the same. Adding reanimated seems to affected other transitions other than the switch. For example all my modal screens inherit the same transition as the one specified for the switch navigator.

Also more related to this lib, my modal screens are doing the closing animation twice when dismissing via navigation.goBack

**Comment by RWOverdijk** [comment]
@brentvatne That's a fair request. I was hoping it was something known so I wouldn't have to make an example. I'll try to make a small example, but I do suspect it's reanimated at work, and not this plugin. But I might be wrong.

**Comment by RWOverdijk** [comment]
Long story short... I've implemented a hacky version of this repo that works better for _me_. After some investigation I got into all sorts of problems with reanimated and the switch unmounting before it's done transitioning, react-navigation's animated `position` being reset hard causing my interpolations to do funky things... etc.

So this library might not be for me. What I did instead is something that's also funky, but... Yeah.

```ts
const AppNavigator = createStackNavigator({
  Splash,
  App,
});

const prevGetStateForAction = AppNavigator.router.getStateForAction;

AppNavigator.router = {
  ...AppNavigator.router,
  getStateForAction(action, state) {
    const { type, key } = action;
    const actionName = 'Navigation/COMPLETE_TRANSITION';

    if (!state || state.routes.length < 2 || type !== actionName || key !== 'StackRouterRoot') {
      return prevGetStateForAction(action, state);
    }

    return {
      ...state,
      index: 0,
      isTransitioning: false,
      routes: [state.routes[1]],
    };
  }
};
```

**Comment by diegolmello** [comment]
Hey everyone.
Here's some gifs.
This is not a switch transition. It's just a normal navigation.
Here's the usage: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/reanimated-switch/app/index.js#L173

## With this lib:
![Apr-08-2019 13-46-20](https://user-images.githubusercontent.com/804994/55742037-14188b80-5a05-11e9-8e4d-7febd3bcf224.gif)

## Without it:
![Apr-08-2019 13-47-24](https://user-images.githubusercontent.com/804994/55742043-1a0e6c80-5a05-11e9-9d9a-3c511ea59e49.gif)

**Comment by brentvatne** [comment]
can someone please provide a minimal reproducible example? :)

**Comment by iRoachie** [comment]
Sure @brentvatne https://github.com/iRoachie/animated-switch-bug-example

**Comment by brentvatne** [comment]
thank you @iRoachie!

**Comment by brentvatne** [comment]
try 0.1.1, i made it so the transition is only animated when the index changes on the switch

**Comment by brentvatne** [comment]
@RWOverdijk - would be super useful to have a minimal reproducible example for your use case

**Comment by RWOverdijk** [comment]
@brentvatne I get that, but it's a bit of a pita to create right now. The icky code I wrote is icky, but works.

Feel free to close this when you feel it's a good idea to do so. I'll provide the example in the future, when I run into it again. You know deadlines :D

**Comment by brentvatne** [comment]
I'll leave this open and hopefully you'll have some time once your deadline comes up to share an example :)
