### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by garciagf05** [react-navigation/animated-switch#18]
Hi.

I am trying to implement a simple switchnavigator, but I get that error when I try to debug. When i remove transition property from createAnimatedSwitchNavigator, app works!

![Captura](https://user-images.githubusercontent.com/38305772/63367769-2c4ccf80-c342-11e9-93fc-42eb113b3d09.PNG)

**package.json dependencies:**
![image](https://user-images.githubusercontent.com/38305772/63373370-68d1f880-c34d-11e9-8e5a-181f635c0b06.png)

**Routes.js**
`import { createStackNavigator, createSwitchNavigator, createAppContainer } from 'react-navigation';
import createAnimatedSwitchNavigator from 'react-navigation-animated-switch';
import { Transition } from 'react-native-reanimated';
import SplashScreen from '../screens/splash/SplashScreen';
import HomeScreen from '../screens/home/HomeScreen';

const AppNavigator = createStackNavigator(
  {
    Home: { screen: HomeScreen },
  },
  {
    headerMode: 'none',
    initialRouteName: 'Home'
  }
);

const InitialNavigator = createAnimatedSwitchNavigator(
  {
    Splash: SplashScreen,
    App: AppNavigator,
  },
  {
    transition: (
      <Transition.Together>
        <Transition.Out
          type="slide-bottom"
          durationMs={400}
          interpolation="easeIn"
        />
        <Transition.In type="fade" durationMs={500} />
      </Transition.Together>
    ),
  }
);

export default createAppContainer(InitialNavigator);
`

**Comment by har2008preet** [comment]
Getting same issue. What was the reason for this? @garciagf05

**Comment by ignitebhdeveloper** [comment]
same issue on android VD Nexus 5 API 24.
`System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5675R CPU @ 3.10GHz
    Memory: 42.88 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.60.5 => 0.60.5
`

**Comment by RZsam** [comment]
in @garciagf05 code Routes.js, he used <Transition> but forgot to 
`import React from 'react'`
