### ISSUE TITLE
Does/Will this work with react-navigation v5?

### ISSUE THREAD

**Issue by pvinis** [react-navigation/animated-switch#38]
Since v5 changed the way navigators are coded, and the old switch navigator is gone (or at least deprecated), is there a way to do an animated switch now?

Will this lib become available and working with v5?

Thanks.

**Comment by satya164** [comment]
You can use stack navigator instead. Use conditionals or `replace` instead `navigate` to achieve similar behavior with animation.

**Comment by pvinis** [comment]
Conditionals don't do animations, but I'll try replace.
