### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/animated-switch#4]
Should be similar to http://github.com/react-navigation/react-navigation-core TS setup

**Comment by PanRada** [comment]
any plans for that ?

**Comment by brentvatne** [comment]
go for it :) it should take like 20 minutes

**Comment by jarvisluong** [comment]
I know this is not a complete solution but I submitted a PR to add ts def here:
https://github.com/react-navigation/animated-switch/issues/4

**Comment by jarvisluong** [comment]
The current challenge is that the type defs of `react-navigation` does not expose `SceneView` and `SwitchRouter` types so ts complains when trying to import them. Maybe I can spend sometimes on updating `react-navigation` type defs to complete this 🤔 ?

**Comment by dsznajder** [comment]
@brentvatne I've created branch with TS. I've followed other repositories for setup and typing.
