### ISSUE TITLE
Screen Out disappear Image, turn to blank screen.

### ISSUE THREAD

**Issue by ducpt2** [react-navigation/animated-switch#8]
Sorry i don't know how to create a repo, here is my code so far:
const MySwitch = createAnimatedSwitchNavigator(
  {
    Home: HomeScreen,  <-- My screen has an image cover all screen.
    Other: OtherScreen,
  },
  {
    transition: (
      <Transition.Together>
        <Transition.Out
          type="slide-left"
          durationMs={400}
          interpolation="easeIn"
        />
        <Transition.In type="fade" durationMs={400}   interpolation="easeIn" />
      </Transition.Together>
    ),
  }
);

And HomeScreen disappear my image, turn to blank and slde left. Maybe i done something wrong. Please help.
Thank you, your library is great.

**Comment by todorone** [comment]
Confirm it `Transition.Out` do not work with `Image` elements, they disappear instantly. It's a problem of `react-native-reanimated`...

**Comment by RZsam** [comment]
Images  disappear in `<Transition.out>` , works correctly for other elements.
is it problem of `react-native-reanimated` or I'm doing something wrong?

        const RootNavigator = createAnimatedSwitchNavigator({
        Splash:{screen:Splash},
        Main:{screen:Main},
        Auth:{screen:Auth},
    },
    {
        transition: (
            <Transition.Sequence>
                <Transition.Out
                    type="slide-left"
                    durationMs={200}
                    interpolation="easeIn"
                />
                <Transition.In
                    type="slide-right"
                    durationMs={200}
                    interpolation="easeOut"
                />
            </Transition.Sequence>
        ),
    },
    );
